### ISSUE TITLE
some export issues

### ISSUE THREAD

**Issue by KasperFranz** [mejrs/rs3cache#8]
Instead of creating a few different issues I thought it would be easier to create one with all of them in

item_configs
<details>
thread 'main' panicked at src/definitions/item_configs.rs:188:28:
not implemented: ItemConfig::deserialize cannot deserialize opcode 178 in id 0
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   3: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: <alloc::collections::btree::map::BTreeMap<K,V> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter
   6: rs3cache::definitions::item_configs::ItemConfig::dump_all
   7: rs3cache::definitions::item_configs::export
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   9: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
  10: rayon::iter::plumbing::bridge_producer_consumer::helper
  11: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
  12: rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
  13: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter
  14: rs3cache::impl_::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</details>

enums
<details>
thread 'main' panicked at src/definitions/enums.rs:301:28:
not implemented: Enum::deserialize cannot deserialize opcode 209 in id 3003
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rs3cache::definitions::enums::Enum::deserialize
   3: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: <alloc::collections::btree::map::BTreeMap<K,V> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter
   6: rs3cache::definitions::enums::Enum::dump_all
   7: rs3cache::definitions::enums::export
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   9: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
  10: rayon::iter::plumbing::bridge_producer_consumer::helper
  11: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
  12: rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
  13: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter
  14: rs3cache::impl_::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</details>

npc_config
<details>
thread 'main' panicked at src/definitions/npc_configs.rs:298:21:
not implemented: NpcConfig::deserialize cannot deserialize opcode 86 in npc:
 {
  "id": 31098,
  "size": 5,
  "actions": [
    null,
    "Attack",
    null,
    null,
    null
  ],
  "combat": 720,
  "unknown_99": false,
  "icon_height": 1280,
  "animation_group": 4357,
  "unknown_159": false,
  "unknown_179": {
    "unknown_1": 15616,
    "unknown_2": 15360,
    "unknown_3": 15360,
    "unknown_4": 17152,
    "unknown_5": 64,
    "unknown_6": 17408
  },
  "unknown_185": 2
}

stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rs3cache::definitions::npc_configs::NpcConfig::deserialize
   3: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: <alloc::collections::btree::map::BTreeMap<K,V> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter
   6: rs3cache::definitions::npc_configs::NpcConfig::dump_all
   7: rs3cache::definitions::npc_configs::export
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   9: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
  10: rayon::iter::plumbing::bridge_producer_consumer::helper
  11: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
  12: rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
  13: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter
  14: rs3cache::impl_::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</details>

There might be more but these are what I have seen so far

**Comment by ceruuuuu** [comment]
item_config output with full backtrace:

`   Dumping [                              ] 0/1: item_configs                                                           thread 'main' panicked at src\definitions\item_configs.rs:188:28:
not implemented: ItemConfig::deserialize cannot deserialize opcode 178 in id 0
stack backtrace:
   0:     0x7ff646c2eddd - <unknown>
   1:     0x7ff646a0a239 - <unknown>
   2:     0x7ff646c2b201 - <unknown>
   3:     0x7ff646c30ef7 - <unknown>
   4:     0x7ff646c30ae9 - <unknown>
   5:     0x7ff646c315b2 - <unknown>
   6:     0x7ff646c31486 - <unknown>
   7:     0x7ff646c2f98f - <unknown>
   8:     0x7ff646c31056 - <unknown>
   9:     0x7ff646d84bd4 - <unknown>
  10:     0x7ff646baf3d7 - <unknown>
  11:     0x7ff646b15cc8 - <unknown>
  12:     0x7ff646b25a73 - <unknown>
  13:     0x7ff646b5b00a - <unknown>
  14:     0x7ff646bbc48f - <unknown>
  15:     0x7ff646bbc5a2 - <unknown>
  16:     0x7ff646bce027 - <unknown>
  17:     0x7ff646bd1cc2 - <unknown>
  18:     0x7ff646b70539 - <unknown>
  19:     0x7ff646b1d0ff - <unknown>
  20:     0x7ff646bc4e54 - <unknown>
  21:     0x7ff646bdcd97 - <unknown>
  22:     0x7ff646b04416 - <unknown>
  23:     0x7ff646b042a0 - <unknown>
  24:     0x7ff646c261b9 - <unknown>
  25:     0x7ff646b0449c - <unknown>
  26:     0x7ff646d8237c - <unknown>
  27:     0x7ff860cedbe7 - BaseThreadInitThunk
  28:     0x7ff8621fa94c - RtlUserThreadStart`
